import os
env = Environment(LIBS=['protobuf'], LIBPATH='/home/jiye/protobuf-2.4.1-install/lib', CPPPATH=['.', '/home/jiye/protobuf-2.4.1-install/include'])
env.Object ('lm.helloworld.pb.cc', )
env.Program (target = "writer", source = ['writer.cpp', 'lm.helloworld.pb.o'])
env.Program (target = "reader", source = ['reader.cpp', 'lm.helloworld.pb.o'])
