Object ('lm.helloworld.pb.cc')
Program (target = "writer", source = ['writer.cpp', 'lm.helloworld.pb.o'], 
		LIBS=['protobuf'], LIBPATH='/home/jiye/protobuf-2.4.1-install/lib', CPPPATH=['.', '/home/jiye/protobuf-2.4.1-install/include'])
Program (target = "reader", source = ['reader.cpp', 'lm.helloworld.pb.o'], 
		LIBS=['protobuf'], LIBPATH='/home/jiye/protobuf-2.4.1-install/lib', CPPPATH=['.', '/home/jiye/protobuf-2.4.1-install/include'])
